### ISSUE TITLE
Update ForestDB to get improved compaction / space reuse

### ISSUE THREAD

**Issue by snej** [couchbaselabs/cbforest#112]
In [CBSE-3058](https://issues.couchbase.com/browse/CBSE-3058) Sundar wrote:

> ForestDB circular block reuse … was designed to solve exactly this type of small-batch-write-space-explosion problem ... The feature was done around December 2015 and was first shipped in 4.5 Couchbase Server watson release. It has been tested extensively by secondary index use cases for both 4.5.1 as well as 4.6 releases. Among other things I believe that it should significantly benefit many mobile device use cases simply because it cuts down the app's write amplification by half.

All we need to do is pull the ForestDB stable branch to the latest. And test...

**Comment by snej** [comment]
Looks like CBForest is already on the current stable commit of forestdb (0e439d55), as of Hideki's commit 7dbcb907 from Sept 13.

I don't know if that means it's already using circular block reuse; I'd guess it has to be enabled explicitly somehow. I'll look at the headers.

**Comment by snej** [comment]
Actually it seems to be enabled by default. Fortunately we haven't released any versions of CBL since this stealth upgrade :)

**Comment by pasin** [comment]
ForestDB team has identified the issue and fixed it.

See https://issues.couchbase.com/browse/MB-21656 for more detail.
