### ISSUE TITLE
ForestDB performance tanking on non SSD Window 10 machine

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/cbforest#115]
Looks like it may be due to compaction.

**Comment by abhinavdangeti** [comment]
If compaction isn't able to catch up with the incoming load to the older file, it is quite possible for the disk usage to shoot up momentarily. Disabling barrier writes would let writer and compactor run without serialization. However if the compactor continues to run slowly even after the load has completed, there could be another issue here.

**Comment by abhinavdangeti** [comment]
Looks a lot like: https://issues.couchbase.com/browse/MB-21656

**Comment by abhinavdangeti** [comment]
Could you make sure that you're using the latest commit on the stable branch?

**Comment by sethrosetter** [comment]
@borrrden Did you see this? Does this happen with latest stable?

**Comment by borrrden** [comment]
Ok, this was a result of couchbase-lite-net not using the latest commit on master here.  There is no issue to resolve in this repo.
