### ISSUE TITLE
Build errors on Windows

### ISSUE THREAD

**Issue by snej** [couchbaselabs/cbforest#13]
@borrrden has been working on getting CBForest to build in MSVC on Windows. Via email:

>Alright, it turns out the errors were not as bad as I thought, just a lot of leaning on GNU extensions.  I was able to get cbforest to “build” on Windows.  The reason I put it in quotes is because I only progressed to the point where all the compile errors were gone.  I didn’t set it up to link with forestdb yet, so I still have linker errors and such to deal with but the core of forestdb compiles now (not sure about the tokenizer library).  I’ve successfully compiled forestDB on Windows before without much of a problem so I don’t imagine it will be much more to do.

>I summarized all the issues I found and how I solved them in this document:  https://docs.google.com/spreadsheets/d/1up0TGzCwKXm7AfYozUgRpQ0zeE707NSxI-xU1dLoaPg/edit?usp=sharing

>I also committed the fixes (minus one from the fts3_unicodesn repo that I don’t have access to) into the feature/c_api _windows branch.

**Comment by snej** [comment]
Oops, Jim already created a PR, #12.

**Comment by borrrden** [comment]
Build errors have been resolved
