### ISSUE TITLE
Encryption is platform-dependent

### ISSUE THREAD

**Issue by borrrden** [couchbaselabs/cbforest#14]
Uses CommonCrypto.  For now it will be good enough to have a compiler directive to either compile or not compile it.

**Comment by snej** [comment]
Encryption has been moved into ForestDB itself (but of course it's still platform dependent.)

**Comment by borrrden** [comment]
Right, I did a little experiment to try to work in a platform independent library, but I stopped when I was foiled by the fact that the Linux prebuilt libtomcrypt static lib from apt-get wasn't compiled with position independent code and I didn't feel like continuing on at that point.  Anyway this issue doesn't need to be open here anymore, but there should be a discussion with the ForestDB team ASAP or this will likely not make it into the 1.2 release.

**Comment by snej** [comment]
We can always fork ForestDB to add this in if we need to.

Can we use the same crypto libraries we're using for SQLCipher? The underlying primitives should be the same (AES-256 and SHA-256.)

**Comment by borrrden** [comment]
Sure we can.  I already set it up to use libtomcrypt, but I got annoyed when I realized I would have to copy over the entire build script from sqlcipher and stopped there, so it hasn't been tested yet.  If you want I can put the untested file into a gist.

**Comment by snej** [comment]
Jim's ForestDB patch is in review on Gerrit now.

**Comment by snej** [comment]
It doesn't look as though the patch was ever merged. I'll check up on it.

**Comment by snej** [comment]
ForestDB issue is [MB-16608](https://issues.couchbase.com/browse/MB-16608), and here's the [Gerrit review](http://review.couchbase.org/#/c/56361/). Looks like it stalled out on the 27th.

**Comment by snej** [comment]
This was just merged into ForestDB a minute ago. I'll update CBForest to pick it up.
