### ISSUE TITLE
Bitfields cause major issues on Windows

### ISSUE THREAD

**Issue by borrrden** [couchbaselabs/cbforest#17]
There is always an issue that I've noticed when assigning bools to 1 bit sections of a bit field.  The bit field representation the compiler chooses is undefined and in the case of Windows it will truncate down to the lowest bit.  The bool value however is 8 bits, which means that there is a 50% chance that the bool will turn into an incorrect value.  For instance in `DocEnumerator.cc` there is this struct:

```
struct Options {
    unsigned                 skip;
    unsigned                 limit;
    bool                     descending     :1;
    bool                     inclusiveStart :1;
    bool                     inclusiveEnd   :1;
    bool                     includeDeleted :1;
    KeyStore::contentOptions contentOptions :4;

    static const Options kDefault;
};
```

And in `C4DocEnumerator* c4db_enumerateAllDocs` in `c4Database.cc` there is this logic:

```
options.descending = c4options->descending;
options.inclusiveStart = c4options->inclusiveStart;
options.inclusiveEnd = c4options->inclusiveEnd;
options.includeDeleted = c4options->includeDeleted;
```

In the unit test run, all four values in c4options are set to `true` and they are all bonafide `bool` types.  However this is less important than what is actually stored inside them, which in this case is (in order) 233, 238, 112, and 5.  To a bool, any value other than ZERO is true.  So why is this a problem?  Well in the bitfield the values get stored as follows:  233 & 1 (1), 238 & 1 (0), 112 & 1 (0), 5 & 1 (1) which turns them into true, false, false, true instead of all true.  Since the comparison is effectively X & 1, this means that the miss rate is about 50%.

There are two ways to deal with this:

1) Don't use bit fields
2) Do the awkward dance of `options.descending = c4options->descending != false`

**Comment by snej** [comment]
This is weird. It’s true that a bool can hold values other than 0 or 1, but in general it shouldn’t, as it only gets initialized by the constants true or false, or by a logical operation like &&.

The values you’re seeing make me suspect something’s wrong. Where did that c4options struct come from? I suspect it may have been allocated/declared without getting initialized, so the fields contain garbage…

**Comment by borrrden** [comment]
The portion of the test I noticed this in was here:

```
C4AllDocsOptions options = kC4DefaultAllDocsOptions;
options.includeBodies = false;
e = c4db_enumerateAllDocs(db, kC4SliceNull, kC4SliceNull, &options, &error);
```

**Comment by snej** [comment]
In that case `kC4DefaultAllDocsOptions` must not be initialized properly … the bools in there should all be 1 or 0. Is MSVC leaving the fields unmentioned in the initializer as garbage?

**Comment by borrrden** [comment]
I have it setup with the C position-based struct initializer (see https://github.com/couchbaselabs/cbforest/blob/feature/c_api/C/c4Database.cc#L611-L618).  I don't quite know what is going on with that.  I could try using (bool)1 I guess.  I'm almost sure it is some weird compiler optimization because the C# bindings don't have this problem.

**Comment by snej** [comment]
Could you set a breakpoint and examine the contents of the struct to see if they're garbage? They shouldn't be, from what I know of the C standard, but it's possible this is a quirk of MSVC…

**Comment by borrrden** [comment]
I already did that, it's how I found the values I noted in the original ticket.  The contents of the struct are weird.  The variable examiner will show things like "true (233)" I wonder which standard is being applied here, because `bool` is a C99 thing and we all know how MSVC fares with C99.  However, it is also a C++ thing.  Everything I look at says "this shouldn't happen" which frustrates me.

**Comment by snej** [comment]
This shouldn't happen. :/ It's in C++ code so there's no problem with `bool`, and you're explicitly initializing every field of the struct to a valid value. If the fields don't have those values at runtime, it seems like the compiler screwed up.

**Comment by borrrden** [comment]
I've found another clue in this matter.  It seems like *ANY* global const struct getting exported for use in CppTests is getting completely blown away for some reason with Visual Studio.  Everything inside of it is garbage.  This garbage just happened to be closer to the truth than the garbage I am dealing with now.
