### ISSUE TITLE
c4view_rekey implementation returns error -30

### ISSUE THREAD

**Issue by borrrden** [couchbaselabs/cbforest#38]
ForestDB rekeys a database by compacting it, however it disallows the compaction of a database file opened with `FDB_SEQTREE_NOT_USE` so the rekey operation cannot succeed.  

(For reference, the location of this check is [here](https://github.com/couchbase/forestdb/blob/c927e44415cc276047c4733b7717af6cfd9c9d94/src/forestdb.cc#L6045-L6047))

**Comment by snej** [comment]
I think in the Obj-C codebase I punted and just erased the view databases during a rekey, since they'll get rebuilt when next queried.

I had no idea you couldn't compact a ForestDB database without a sequence tree — that seems very weird. I'll ask the devs.
