### ISSUE TITLE
Java View.beginIndex doesn't support multiple view indexing

### ISSUE THREAD

**Issue by pasin** [couchbaselabs/cbforest#47]
Can we make the interface below support multiple view indexing?

https://github.com/couchbaselabs/cbforest/blob/d0afb82139a4e992c734b183628a5f195d1182ef/Java/jni/native_view.cc#L124-L134

**Comment by hideki** [comment]
This blocks to fix https://github.com/couchbase/couchbase-lite-java-core/issues/681

**Comment by snej** [comment]
The intent is that you can create multiple `c4Indexer`s at the same time, and then iterate through the docs once, feeding each indexer its keys and values.

Looking at the API, what's missing is a version of `c4indexer_enumerateDocuments` that takes multiple indexers as input, computes the earliest sequence that needs to be indexed, and starts from there. Should be easy to do.

**Comment by pasin** [comment]
@snej I think the enumerateDocuments logic that you described above has already implemented as `C4Indexer` extended from MapReduceIndexer. The only missing piece is that multiple views if available should be given to `c4indexer_begin()` instead of only just 1 from the current view (See [beginIndex](https://github.com/couchbaselabs/cbforest/blob/d0afb82139a4e992c734b183628a5f195d1182ef/Java/jni/native_view.cc#L124-L134) code). Probably we also need to extract an `Indexer` class from the [View](https://github.com/couchbaselabs/cbforest/blob/d0afb82139a4e992c734b183628a5f195d1182ef/Java/src/com/couchbase/cbforest/View.java) class in order to do that.

**Comment by snej** [comment]
Just uploaded PR #48 to support this.
