### ISSUE TITLE
strlcpy() is BSD-only

### ISSUE THREAD

**Issue by jpetso** [couchbaselabs/cbforest#7]
Something I haven't fixed in my latest pull request #6 is the use of strlcpy(), which doesn't exist on Linux/glibc and presumably other platforms. Maybe there's a different way to implement the same thing with a more portable function?

**Comment by snej** [comment]
Crap, this happens every time I use strlcpy — it always ends up in some cross-platform code that someone tries to build on Linux ;-)

Maybe you could add a static implementation of strlcpy and #ifdef it appropriately for non-BSD platforms?

**Comment by jpetso** [comment]
I can probably do that. I wonder whether in this case, it would be easier to move the one-liner to the .cc file and add one or two lines of length checking, akin to http://stackoverflow.com/a/2115073. I'm not sure what you intend to happen if the string doesn't fit - right now, no error is returned and the string is just cut off (with zero termination due to strlcpy).

**Comment by jpetso** [comment]
I found that the other constructor is doing something very similar (and concise) already, so I adapted its code and used it for the const char* constructor. Added a commit to my pull request #6, this should be the last one to add. (I still need to make sqlite3-unicodesn build within my CMake build but in terms of code portability it's looking good now.)

**Comment by jpetso** [comment]
Fixed by commit eabd5ee93216e3653f682fbf7c92ca4ba441191f.
